//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <summary>
   /// Адрес
   /// </summary>
   [System.ComponentModel.Description("Адрес")]
   public partial class Address
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Address()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Address CreateAddressUnsafe()
      {
         return new Address();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="region"></param>
      /// <param name="district"></param>
      /// <param name="town"></param>
      /// <param name="street"></param>
      /// <param name="house"></param>
      /// <param name="_patient0"></param>
      public Address(string region, string district, string town, string street, string house, global::CovidDoc.Model.Patient _patient0)
      {
         if (string.IsNullOrEmpty(region)) throw new ArgumentNullException(nameof(region));
         this.Region = region;

         if (string.IsNullOrEmpty(district)) throw new ArgumentNullException(nameof(district));
         this.District = district;

         if (string.IsNullOrEmpty(town)) throw new ArgumentNullException(nameof(town));
         this.Town = town;

         if (string.IsNullOrEmpty(street)) throw new ArgumentNullException(nameof(street));
         this.Street = street;

         if (string.IsNullOrEmpty(house)) throw new ArgumentNullException(nameof(house));
         this.House = house;

         if (_patient0 == null) throw new ArgumentNullException(nameof(_patient0));
         _patient0.RegAddress = this;

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="region"></param>
      /// <param name="district"></param>
      /// <param name="town"></param>
      /// <param name="street"></param>
      /// <param name="house"></param>
      /// <param name="_patient0"></param>
      public static Address Create(string region, string district, string town, string street, string house, global::CovidDoc.Model.Patient _patient0)
      {
         return new Address(region, district, town, street, house, _patient0);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Регион")]
      public string Region { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Район")]
      public string District { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Город")]
      public string Town { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Улица")]
      public string Street { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Дом")]
      public string House { get; set; }

      /// <summary>
      /// Indexed, Max length = 255
      /// </summary>
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Строение")]
      public string Building { get; set; }

      /// <summary>
      /// Indexed, Max length = 255
      /// </summary>
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Квартира")]
      public string Appartment { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

   }
}

