//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <summary>
   /// Роль пользователя
   /// </summary>
   [System.ComponentModel.Description("Роль пользователя")]
   public partial class AppRole
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public AppRole()
      {
         Users = new System.Collections.Generic.HashSet<global::CovidDoc.Model.AppUser>();

         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="name"></param>
      /// <param name="code"></param>
      /// <param name="_statustransition0"></param>
      public AppRole(string name, string code, global::CovidDoc.Model.StatusTransition _statustransition0)
      {
         if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
         this.Name = name;

         if (string.IsNullOrEmpty(code)) throw new ArgumentNullException(nameof(code));
         this.Code = code;

         if (_statustransition0 == null) throw new ArgumentNullException(nameof(_statustransition0));
         _statustransition0.GrantedForRoles.Add(this);

         Users = new System.Collections.Generic.HashSet<global::CovidDoc.Model.AppUser>();
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="name"></param>
      /// <param name="code"></param>
      /// <param name="_statustransition0"></param>
      public static AppRole Create(string name, string code, global::CovidDoc.Model.StatusTransition _statustransition0)
      {
         return new AppRole(name, code, _statustransition0);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      public string Name { get; set; }

      /// <summary>
      /// Required, Max length = 50
      /// </summary>
      [Required]
      [MaxLength(50)]
      [StringLength(50)]
      public string Code { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      [Display(Name="Пользователи имполняющие роль")]
      public virtual ICollection<global::CovidDoc.Model.AppUser> Users { get; private set; }

   }
}

