//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <summary>
   /// Врач
   /// </summary>
   [System.ComponentModel.Description("Врач")]
   public partial class Doctor: global::CovidDoc.Model.AppUser
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Doctor(): base()
      {
         ReferralItems = new System.Collections.Generic.HashSet<global::CovidDoc.Model.ReferralItem>();

         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="username"></param>
      /// <param name="password"></param>
      /// <param name="fio"></param>
      /// <param name="disabled"></param>
      /// <param name="organization"></param>
      /// <param name="_document0"></param>
      public Doctor(string username, string password, string fio, global::CovidDoc.Model.Organization organization, global::CovidDoc.Model.Document _document0, bool disabled = false)
      {
         if (string.IsNullOrEmpty(username)) throw new ArgumentNullException(nameof(username));
         this.UserName = username;

         if (string.IsNullOrEmpty(password)) throw new ArgumentNullException(nameof(password));
         this.Password = password;

         if (string.IsNullOrEmpty(fio)) throw new ArgumentNullException(nameof(fio));
         this.Fio = fio;

         this.Disabled = disabled;

         if (organization == null) throw new ArgumentNullException(nameof(organization));
         this.Organization = organization;
         organization.AppUsers.Add(this);

         if (_document0 == null) throw new ArgumentNullException(nameof(_document0));
         _document0.ModifiedByUser.Add(this);

         ReferralItems = new System.Collections.Generic.HashSet<global::CovidDoc.Model.ReferralItem>();
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="username"></param>
      /// <param name="password"></param>
      /// <param name="fio"></param>
      /// <param name="disabled"></param>
      /// <param name="organization"></param>
      /// <param name="_document0"></param>
      public static new Doctor Create(string username, string password, string fio, global::CovidDoc.Model.Organization organization, global::CovidDoc.Model.Document _document0, bool disabled = false)
      {
         return new Doctor(username, password, fio, organization, _document0, disabled);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      [Display(Name="Направления")]
      public virtual ICollection<global::CovidDoc.Model.ReferralItem> ReferralItems { get; private set; }

   }
}

