//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <summary>
   /// Документ
   /// </summary>
   [System.ComponentModel.Description("Документ")]
   public abstract partial class Document
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Document()
      {
         ModifiedByUser = new System.Collections.Generic.HashSet<global::CovidDoc.Model.AppUser>();
         Signatures = new System.Collections.Generic.HashSet<global::CovidDoc.Model.Signature>();

         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="createdatetime"></param>
      /// <param name="modifydatetime"></param>
      /// <param name="documentdate"></param>
      /// <param name="organization"></param>
      /// <param name="createbyuser"></param>
      /// <param name="documentstatus"></param>
      protected Document(DateTime createdatetime, DateTime modifydatetime, DateTime documentdate, global::CovidDoc.Model.Organization organization, global::CovidDoc.Model.AppUser createbyuser, global::CovidDoc.Model.DocumentStatus documentstatus)
      {
         this.CreateDateTime = createdatetime;

         this.ModifyDateTime = modifydatetime;

         this.DocumentDate = documentdate;

         if (organization == null) throw new ArgumentNullException(nameof(organization));
         this.Organization = organization;
         organization.Documents.Add(this);

         if (createbyuser == null) throw new ArgumentNullException(nameof(createbyuser));
         this.CreateByUser = createbyuser;
         createbyuser.CreatedDocuments.Add(this);

         if (documentstatus == null) throw new ArgumentNullException(nameof(documentstatus));
         this.DocumentStatus = documentstatus;
         documentstatus.Documents.Add(this);

         ModifiedByUser = new System.Collections.Generic.HashSet<global::CovidDoc.Model.AppUser>();
         Signatures = new System.Collections.Generic.HashSet<global::CovidDoc.Model.Signature>();
         Init();
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      [Display(Name="Создано")]
      public DateTime CreateDateTime { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      [Display(Name="Изменено")]
      public DateTime ModifyDateTime { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      [Display(Name="Дата документа")]
      public DateTime DocumentDate { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      [Display(Name="Изменил")]
      public virtual ICollection<global::CovidDoc.Model.AppUser> ModifiedByUser { get; private set; }

      [Display(Name="Электронные подписи")]
      public virtual ICollection<global::CovidDoc.Model.Signature> Signatures { get; private set; }

      /// <summary>
      /// Required
      /// </summary>
      [Display(Name="Организация")]
      public virtual global::CovidDoc.Model.Organization Organization { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Display(Name="Создал")]
      public virtual global::CovidDoc.Model.AppUser CreateByUser { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Display(Name="Статус")]
      public virtual global::CovidDoc.Model.DocumentStatus DocumentStatus { get; set; }

   }
}

