//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <summary>
   /// Сведения о госпитализации
   /// </summary>
   [System.ComponentModel.Description("Сведения о госпитализации")]
   public partial class Hospitalization
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Hospitalization()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Hospitalization CreateHospitalizationUnsafe()
      {
         return new Hospitalization();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="begindate"></param>
      /// <param name="hospitalname"></param>
      /// <param name="_referralitem0"></param>
      public Hospitalization(DateTime begindate, string hospitalname, global::CovidDoc.Model.ReferralItem _referralitem0)
      {
         this.BeginDate = begindate;

         if (string.IsNullOrEmpty(hospitalname)) throw new ArgumentNullException(nameof(hospitalname));
         this.HospitalName = hospitalname;

         if (_referralitem0 == null) throw new ArgumentNullException(nameof(_referralitem0));
         _referralitem0.Hospitalization = this;

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="begindate"></param>
      /// <param name="hospitalname"></param>
      /// <param name="_referralitem0"></param>
      public static Hospitalization Create(DateTime begindate, string hospitalname, global::CovidDoc.Model.ReferralItem _referralitem0)
      {
         return new Hospitalization(begindate, hospitalname, _referralitem0);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      [Display(Name="Дата начала")]
      public DateTime BeginDate { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Наименование лечебного учреждения")]
      public string HospitalName { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

   }
}

