//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <summary>
   /// Документ удостоверяющий личность
   /// </summary>
   [System.ComponentModel.Description("Документ удостоверяющий личность")]
   public partial class IdentityDocument
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public IdentityDocument()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="serial"></param>
      /// <param name="number"></param>
      /// <param name="patient"></param>
      /// <param name="identitydocumenttype"></param>
      public IdentityDocument(string serial, string number, global::CovidDoc.Model.Patient patient, global::CovidDoc.Model.IdentityDocumentType identitydocumenttype)
      {
         if (string.IsNullOrEmpty(serial)) throw new ArgumentNullException(nameof(serial));
         this.Serial = serial;

         if (string.IsNullOrEmpty(number)) throw new ArgumentNullException(nameof(number));
         this.Number = number;

         if (patient == null) throw new ArgumentNullException(nameof(patient));
         this.Patient = patient;
         patient.IdentityDocuments.Add(this);

         if (identitydocumenttype == null) throw new ArgumentNullException(nameof(identitydocumenttype));
         this.IdentityDocumentType = identitydocumenttype;
         identitydocumenttype.IdentityDocuments.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="serial"></param>
      /// <param name="number"></param>
      /// <param name="patient"></param>
      /// <param name="identitydocumenttype"></param>
      public static IdentityDocument Create(string serial, string number, global::CovidDoc.Model.Patient patient, global::CovidDoc.Model.IdentityDocumentType identitydocumenttype)
      {
         return new IdentityDocument(serial, number, patient, identitydocumenttype);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Серия")]
      public string Serial { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Номер")]
      public string Number { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      [Display(Name="Пациент")]
      public virtual global::CovidDoc.Model.Patient Patient { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Display(Name="Тип документа")]
      public virtual global::CovidDoc.Model.IdentityDocumentType IdentityDocumentType { get; set; }

   }
}

