//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <summary>
   /// Пациент
   /// </summary>
   [System.ComponentModel.Description("Пациент")]
   public partial class Patient
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Patient()
      {
         Sex = 2;
         Phone = "Номер телефона";
         Policy = "Номер полиса ОМС единого образца";
         IdentityDocuments = new System.Collections.Generic.HashSet<global::CovidDoc.Model.IdentityDocument>();
         ReferralItems = new System.Collections.Generic.HashSet<global::CovidDoc.Model.ReferralItem>();
         Works = new System.Collections.Generic.HashSet<global::CovidDoc.Model.Work>();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Patient CreatePatientUnsafe()
      {
         return new Patient();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="lastname"></param>
      /// <param name="firstname"></param>
      /// <param name="birthdate"></param>
      /// <param name="sex"></param>
      /// <param name="snils"></param>
      /// <param name="phone"></param>
      /// <param name="policy"></param>
      /// <param name="factaddress"></param>
      public Patient(string lastname, string firstname, DateTime birthdate, string snils, global::CovidDoc.Model.Address factaddress, byte sex = 2, string phone = "Номер телефона", string policy = "Номер полиса ОМС единого образца")
      {
         if (string.IsNullOrEmpty(lastname)) throw new ArgumentNullException(nameof(lastname));
         this.LastName = lastname;

         if (string.IsNullOrEmpty(firstname)) throw new ArgumentNullException(nameof(firstname));
         this.FirstName = firstname;

         this.BirthDate = birthdate;

         this.Sex = sex;

         if (string.IsNullOrEmpty(snils)) throw new ArgumentNullException(nameof(snils));
         this.Snils = snils;

         if (string.IsNullOrEmpty(phone)) throw new ArgumentNullException(nameof(phone));
         this.Phone = phone;

         if (string.IsNullOrEmpty(policy)) throw new ArgumentNullException(nameof(policy));
         this.Policy = policy;

         if (factaddress == null) throw new ArgumentNullException(nameof(factaddress));
         this.FactAddress = factaddress;

         IdentityDocuments = new System.Collections.Generic.HashSet<global::CovidDoc.Model.IdentityDocument>();
         ReferralItems = new System.Collections.Generic.HashSet<global::CovidDoc.Model.ReferralItem>();
         Works = new System.Collections.Generic.HashSet<global::CovidDoc.Model.Work>();
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="lastname"></param>
      /// <param name="firstname"></param>
      /// <param name="birthdate"></param>
      /// <param name="sex"></param>
      /// <param name="snils"></param>
      /// <param name="phone"></param>
      /// <param name="policy"></param>
      /// <param name="factaddress"></param>
      public static Patient Create(string lastname, string firstname, DateTime birthdate, string snils, global::CovidDoc.Model.Address factaddress, byte sex = 2, string phone = "Номер телефона", string policy = "Номер полиса ОМС единого образца")
      {
         return new Patient(lastname, firstname, birthdate, snils, factaddress, sex, phone, policy);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Фамилия")]
      public string LastName { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Имя")]
      public string FirstName { get; set; }

      /// <summary>
      /// Indexed, Max length = 255
      /// </summary>
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="Отчество")]
      public string PatrName { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      [Display(Name="Дата рождения")]
      public DateTime BirthDate { get; set; }

      /// <summary>
      /// Required, Default value = 2
      /// </summary>
      [Required]
      [Display(Name="Пол")]
      public byte Sex { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="СНИЛС")]
      public string Snils { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255, Default value = &quot;Номер телефона&quot;
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      public string Phone { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255, Default value = &quot;Номер полиса ОМС единого образца&quot;
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      public string Policy { get; set; }

      /// <summary>
      /// Indexed, Max length = 255
      /// </summary>
      [MaxLength(255)]
      [StringLength(255)]
      [Display(Name="ФИО родителя")]
      public string ParentFio { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      [Display(Name="Адрес регистрации")]
      public virtual global::CovidDoc.Model.Address RegAddress { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Display(Name="Адрес проживания")]
      public virtual global::CovidDoc.Model.Address FactAddress { get; set; }

      [Display(Name="Удостоверения личности")]
      public virtual ICollection<global::CovidDoc.Model.IdentityDocument> IdentityDocuments { get; private set; }

      [Display(Name="Направления")]
      public virtual ICollection<global::CovidDoc.Model.ReferralItem> ReferralItems { get; private set; }

      [Display(Name="Места работы")]
      public virtual ICollection<global::CovidDoc.Model.Work> Works { get; private set; }

   }
}

