//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <remarks>
   /// Пакет направлений
   /// </remarks>
   public partial class ReferralPack: global::CovidDoc.Model.Document
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected ReferralPack(): base()
      {
         ReferralItems = new System.Collections.Generic.HashSet<global::CovidDoc.Model.ReferralItem>();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static ReferralPack CreateReferralPackUnsafe()
      {
         return new ReferralPack();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="createdatetime"></param>
      /// <param name="modifydatetime"></param>
      /// <param name="documentdate"></param>
      /// <param name="laboratory"></param>
      /// <param name="organization"></param>
      /// <param name="createbyuser"></param>
      /// <param name="documentstatus"></param>
      public ReferralPack(DateTime createdatetime, DateTime modifydatetime, DateTime documentdate, global::CovidDoc.Model.Organization laboratory, global::CovidDoc.Model.Organization organization, global::CovidDoc.Model.AppUser createbyuser, global::CovidDoc.Model.DocumentStatus documentstatus)
      {
         this.CreateDateTime = createdatetime;

         this.ModifyDateTime = modifydatetime;

         this.DocumentDate = documentdate;

         if (laboratory == null) throw new ArgumentNullException(nameof(laboratory));
         this.Laboratory = laboratory;

         if (organization == null) throw new ArgumentNullException(nameof(organization));
         this.Organization = organization;
         organization.Documents.Add(this);

         if (createbyuser == null) throw new ArgumentNullException(nameof(createbyuser));
         this.CreateByUser = createbyuser;
         createbyuser.CreatedDocuments.Add(this);

         if (documentstatus == null) throw new ArgumentNullException(nameof(documentstatus));
         this.DocumentStatus = documentstatus;
         documentstatus.Documents.Add(this);

         ReferralItems = new System.Collections.Generic.HashSet<global::CovidDoc.Model.ReferralItem>();
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="createdatetime"></param>
      /// <param name="modifydatetime"></param>
      /// <param name="documentdate"></param>
      /// <param name="laboratory"></param>
      /// <param name="organization"></param>
      /// <param name="createbyuser"></param>
      /// <param name="documentstatus"></param>
      public static ReferralPack Create(DateTime createdatetime, DateTime modifydatetime, DateTime documentdate, global::CovidDoc.Model.Organization laboratory, global::CovidDoc.Model.Organization organization, global::CovidDoc.Model.AppUser createbyuser, global::CovidDoc.Model.DocumentStatus documentstatus)
      {
         return new ReferralPack(createdatetime, modifydatetime, documentdate, laboratory, organization, createbyuser, documentstatus);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      [Display(Name="Лаборатория")]
      public virtual global::CovidDoc.Model.Organization Laboratory { get; set; }

      [Display(Name="Направления")]
      public virtual ICollection<global::CovidDoc.Model.ReferralItem> ReferralItems { get; private set; }

   }
}

