//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace CovidDoc.Model
{
   /// <summary>
   /// Сведения о вакцинации
   /// </summary>
   [System.ComponentModel.Description("Сведения о вакцинации")]
   public partial class Vaccination
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Vaccination()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="lastvaccinationdate"></param>
      /// <param name="vaccinetype"></param>
      /// <param name="_referralitem0"></param>
      public Vaccination(DateTime lastvaccinationdate, global::CovidDoc.Model.VaccineType vaccinetype, global::CovidDoc.Model.ReferralItem _referralitem0)
      {
         this.LastVaccinationDate = lastvaccinationdate;

         if (vaccinetype == null) throw new ArgumentNullException(nameof(vaccinetype));
         this.VaccineType = vaccinetype;
         vaccinetype.Vaccinations.Add(this);

         if (_referralitem0 == null) throw new ArgumentNullException(nameof(_referralitem0));
         _referralitem0.Vaccination = this;

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="lastvaccinationdate"></param>
      /// <param name="vaccinetype"></param>
      /// <param name="_referralitem0"></param>
      public static Vaccination Create(DateTime lastvaccinationdate, global::CovidDoc.Model.VaccineType vaccinetype, global::CovidDoc.Model.ReferralItem _referralitem0)
      {
         return new Vaccination(lastvaccinationdate, vaccinetype, _referralitem0);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      [Display(Name="Дата постановки последней компоненты ввакцины")]
      public DateTime LastVaccinationDate { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      [Display(Name="Тип вакцины")]
      public virtual global::CovidDoc.Model.VaccineType VaccineType { get; set; }

   }
}

